### ISSUE TITLE
Cancel of opening

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb#55]
If you click on the "Open" button inside "File", and then cancel the search, the following error will occur:

```
Traceback (most recent call last):
  File "d:\conda3\envs\nfb_studio\lib\site-packages\pynfb\main.py", line 78, in open_event
    params = xml_file_to_params(fname)
  File "d:\conda3\envs\nfb_studio\lib\site-packages\pynfb\serializers\xml_.py", line 70, in xml_file_to_params
    d = vectors_defaults if filename is None else xml_file_to_odict(filename)
  File "d:\conda3\envs\nfb_studio\lib\site-packages\pynfb\serializers\xml_.py", line 56, in xml_file_to_odict
    with open(filename_or_str, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by andreasxp** [comment]
Fixed in branch `0.1`.
